---
title: "Compute wilting curves"
output: html_notebook
---

Load packages

```{r}
library(ggplot2)
library(ggpubr)
library(tidyverse)
```
Parameters for plotting:

```{r}
my.theme<-theme(axis.text=element_text(size=12),
        axis.title = element_text(size = 14),
        legend.text=element_text(size=10),
        legend.title = element_text(size=12),
        plot.title = element_text(face="bold",size=14,margin=margin(0,0,20,0),hjust = 0.5),
        axis.title.y = element_text(hjust = 0.5),
        axis.title.x = element_text(hjust = 0.5))
```

Load dataset:

```{r}

Dataset <- read.csv("../dataset.csv")

Dataset <- Dataset %>%  # filter data for between population crosses
  filter(w_b == "b") 

```


## Create wilting curves plot


```{r}

# Convert wilting measurements into binary values
wilting_binary <- Dataset %>%
  mutate_at(vars(starts_with("wilt")), ~ ifelse(. != "", 1, 0)) %>%
  select(trt, colors, starts_with("wilt")) %>%
  pivot_longer(cols = starts_with("wilt"), names_to = "measurement", values_to = "wilting")

# Rename measurements
wilting_binary$measurement <- as.numeric(gsub("wilt", "", wilting_binary$measurement))

# Group by treatment, color, and wilting measurement, and count the number of wilting individuals
wilting_counts <- wilting_binary %>%
  group_by(trt, colors, measurement) %>%
  summarise(wilting_count = sum(wilting)) %>%
  ungroup()

# Plot for control treatment
p_c <- ggplot(wilting_counts %>% filter(trt == "control"), aes(x = measurement, y = wilting_count, group = colors, color = colors)) +
  geom_line(size = 1) + geom_point(size = 2) +
  scale_color_manual(values = c("#990099", "#FF6666", "yellow"), labels = c("pseudomajus", "F1 hybrid", "striatum")) +
  ylab("Number of Wilting Individuals") +
  xlab("Week") +
  ylim(0,17.5)+
  labs(color = "Phenotype") +
  theme_classic() +
  my.theme

# Plot for early drought treatment
p_e <- ggplot(wilting_counts %>% filter(trt == "early drought"), aes(x = measurement, y = wilting_count, group = colors, color = colors)) +
  geom_line(size = 1) + geom_point(size = 2) +
  scale_color_manual(values = c("#990099", "#FF6666", "yellow"), labels = c("pseudomajus", "F1 hybrid", "striatum")) +
  ylab("Number of Wilting Individuals") +
  xlab("Week") +
  ylim(0,17.5)+
  labs(color = "Phenotype") +
  theme_classic() +
  my.theme

# Plot for late drought treatment
p_l <- ggplot(wilting_counts %>% filter(trt == "late drought"), aes(x = measurement, y = wilting_count, group = colors, color = colors)) +
  geom_line(size = 1) + geom_point(size = 2) +
  scale_color_manual(values = c("#990099", "#FF6666", "yellow"), labels = c("pseudomajus", "F1 hybrid", "striatum")) +
  ylab("Number of Wilting Individuals") +
  xlab("Week") +
  ylim(0,17.5)+
  labs(color = "Phenotype") +
  theme_classic() +
  my.theme


p_c <- p_c + labs(color = "morphotype")
p_e <- p_e + labs(color = "morphotype")
p_l <- p_l + labs(color = "morphotype")

plot_wilting <- ggarrange(
  p_c,
  p_e,
  p_l,
  nrow = 1,
  ncol = 3,
  common.legend = TRUE,
  labels = c("A", "B", "C")
)

plot_wilting


#ggsave("../figures/plot_S4.png", height = 5.5, width = 13)

```



